# -*- coding: utf-8 -*-
"""Despliegue_Proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkudNmlJ34tB4GNFo4LXhWYst2ZJQsuI

# Poryecto Churn en banca

Predicción de Fuga
"""

#Importamos librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

#Cargamos el modelo
import pickle
filename = 'modelo.pkl'
modelo,variables = pickle.load(open(filename, 'rb'))

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de fuga de clientes')

CreditScore = st.slider('Puntaje Crediticio', min_value=200, max_value=800, value=200, step=1)
Geography = st.selectbox('País', ['France', 'Germany','Spain'])
Gender = st.selectbox('Género', ['Male', 'Female'])
Age = st.slider('Edad', min_value=18, max_value=150, value=20, step=1)
Tenure = st.slider('Antiguedad', min_value=0, max_value=150, value=0, step=1)
Balance = st.slider('Balance', min_value=0, max_value=10000000, value=0, step=1)
NumOfProducts = st.slider('Numero de Productos', min_value=1, max_value=5, value=1, step=1)
ItsActiveMember = st.selectbox('Es Miembro Activo', [1, 0])
EstimatedSalary = st.slider('Salario Estimado', min_value=0, max_value=10000000, value=0, step=1)

datos = [[CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, ItsActiveMember, EstimatedSalary]]
data = pd.DataFrame(datos, columns=['CreditScore', 'Geography', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'ItsActiveMember', 'EstimatedSalary']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación debe ser igual al aprendizaje
data_preparada=data.copy()
data_preparada = pd.get_dummies(data_preparada, columns=['Gender','Geography'], drop_first=False, dtype=int) #Despliegue siempre drop_first en false
data_preparada.head()

#Se adicionan las columnas faltantes
data_preparada=data_preparada.reindex(columns=variables,fill_value=0)
data_preparada.head()

#Hacemos la predicción con el modelo
Y_fut = modelo.predict(data_preparada)
print(Y_fut)

data['Predicción']= Y_fut
data.head()

"""Evaluación del Modelo

La calidad del modelo es:

Exactitud: 0.852395

Precisión: 0.852400

Recall: 0.807907

F1 Score: 0.823747
"""